export const SHOW_EDIT_BOOK_MODAL = 'SHOW_EDIT_BOOK_MODAL';
export const CLOSE_EDIT_BOOK_MODAL = 'CLOSE_EDIT_BOOK_MODAL';
export const SHOW_DELETE_BOOK_MODAL = 'SHOW_DELETE_BOOK_MODAL';
export const CLOSE_DELETE_BOOK_MODAL = 'CLOSE_DELETE_BOOK_MODAL';
export const DELETE_BOOK = 'DELETE_BOOK';
